### ISSUE TITLE
Can i use this compiler with visual studio?

### ISSUE THREAD

**Issue by Buntu0001** [bluesadi/Pluto-Obfuscator#10]
I want to use this compiler with visual studio.
Is this compiler can work with visual studio 2022?

**Comment by bluesadi** [comment]
Of course. You can refer to the following commands, which will generate a VS project:
```
cd build
cmake -G "Visual Studio 17 2022" -DLLVM_ENABLE_PROJECTS="clang" \
    -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86" \
    -DBUILD_SHARED_LIBS=On ../llvm
```
Reference from https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2017%202022.html

**Comment by bluesadi** [comment]
What's more, the MBAObfuscation depends on z3-solver. So you need to install libz3 on your Windows machine. I haven't tried it yet.

**Comment by Buntu0001** [comment]
i got some error while compile on Visual Studio 2022
![image](https://user-images.githubusercontent.com/57615703/158173331-d2da137e-651b-4628-902c-51d5aff7910e.png)
