### ISSUE TITLE
Obfuscation/MBAUtils.h:1:10: fatal error: 'z3++.h' file not found

### ISSUE THREAD

**Issue by HuErr** [bluesadi/Pluto-Obfuscator#12]
按照看雪的教程编译win ndk，但是出现这个，我已经安装了 sudo apt install libz3-dev ,测试没有用。我又在 ~/llvm-toolchain/toolchain/llvm-project/llvm/lib/Transforms/IPO/CMakeLists.txt 中添加了，也没起到作用。

include_directories ("/usr/include/")
link_directories("/usr/lib/x86_64-linux-gnu/")

**Comment by lasting-yang** [comment]
我的ubuntu已经使用以下命令安装z3，还是会提示z3++.h file not found
```
sudo apt install libz3-dev 
```

后来进行了如下修改，编译通过
llvm/lib/Transforms/Obfuscation/CMakeLists.txt

```
find_package(z3 REQUIRED)

add_llvm_component_library(LLVMObfuscation
  HelloWorld.cpp
  CryptoUtils.cpp
  Flattening.cpp
  MBAUtils.cpp
  MBAObfuscation.cpp
  Substitution.cpp
  IndirectCall.cpp
  BogusControlFlow.cpp
  GlobalEncryption.cpp
  Pipeline.cpp

  LINK_COMPONENTS
  Core
  Support
  Analysis
  TransformUtils
  
  LINK_LIBS
  ${Z3_LIBRARIES}
  )

```
