### ISSUE TITLE
GlobalEncryption exposing my cpp names

### ISSUE THREAD

**Issue by VanHoevenTR** [bluesadi/Pluto-Obfuscator#18]
Why does GlobalEncryption turn some functions as EXPORT and expose my cpp names, even though i did aggressively strip functions? Is there any fix?

![image](https://user-images.githubusercontent.com/70694330/168872186-65b7141a-6856-4975-9919-612529c8663a.png)

**Comment by Ylarod** [comment]
Related Code: [llvm/lib/IR/Module.cpp#L149](https://github.com/bluesadi/Pluto-Obfuscator/blob/2c6202b6ed57aed25a7a82eac9fd53fb3fa091a6/llvm/lib/IR/Module.cpp#L149)

This may be solved by hashing the generated function name.
