### ISSUE TITLE
已经编译别的llvm项目（已有build文件夹），如何再编译这个项目呢（还在之前build文件夹中进行还是需要怎么做呢）

### ISSUE THREAD

**Issue by xhjhkx** [bluesadi/Pluto-Obfuscator#38]
已经编译别的llvm项目（已有build文件夹），如何再编译这个项目呢（还在之前build文件夹中进行还是需要怎么做呢）

**Comment by bluesadi** [comment]
你可以在任何文件夹里面编译这个项目，文件夹的名字不一定要是`build`，`build2`啥的的也可以
