### ISSUE TITLE
LLVMObfuscator.so missing

### ISSUE THREAD

**Issue by iraizo** [bluesadi/Pluto-Obfuscator#4]
compiling using 
```bash
cd build
cmake -G "Ninja" -DLLVM_ENABLE_PROJECTS="clang" \
    -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86" \
    -DBUILD_SHARED_LIBS=On ../llvm
ninja
```
on macOS does not seem to compile `LLVMObfuscator.so` but anything else

**Comment by bluesadi** [comment]
I need to check out the compiling log. Can you share it?

**Comment by iraizo** [comment]
Will do later today

**Comment by nullhook** [comment]
related: https://github.com/bluesadi/Pluto-Obfuscator/issues/8
