### ISSUE TITLE
[MacOS] don't hardcode z3lib.so and build errors 

### ISSUE THREAD

**Issue by nullhook** [bluesadi/Pluto-Obfuscator#8]
if you want this to be cross-platform do not hardcode `link_libraries("/usr/lib/libz3.so")`. Perhaps add a dep requirement in the readme and if/else OS directive? 

i have installed z3 via homebrew and it triggers the build: `link_libraries("/opt/homebrew/lib/libz3.dylib")` 

however, I get lots of build warnings and errors half way.

`.../Obfuscation/CryptoUtils.h:68:2: error: "Unknown endianness of the compilation platform, check this header aes_encrypt.h"
#error`

**Comment by SsageParuders** [comment]
For MacBook Pro with M1.
https://github.com/obfuscator-llvm/obfuscator/pull/160
patch `CryptoUtils.h` just as:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/75780727/155286195-89939099-9ccb-4e05-9100-4323817b8576.png">

**Comment by bluesadi** [comment]
Changed to:
```
add_llvm_component_library(LLVMObfuscation
  HelloWorld.cpp
  SplitBasicBlock.cpp
  CryptoUtils.cpp
  Utils.cpp
  Flattening.cpp
  BogusControlFlow.cpp
  Substitution.cpp
  GlobalsEncryption.cpp
  VariableSubstitution.cpp
  RandomControlFlow.cpp
  TrapAngr.cpp
  LinearMBAObfuscation.cpp
  MBAUtils.cpp

  DEPENDS
  intrinsics_gen
  
  LINK_LIBS
  z3

  LINK_COMPONENTS
  Core
  Support
  Analysis
  TransformUtils
)
```
